name: Publish Python Package TestPyPi

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/mindm
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip
        cache-dependency-path: pyproject.toml 
    - name: Install dependencies
      run: |
        pip install setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/