name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Build and Publish TestPyPi"]
    types:
      - completed
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
        continue-on-error: true
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Rebuild documentation if the artifact is not available
      - name: Build documentation if needed
        if: steps.download.outcome != 'success'
        run: |
          # Install all requirements at once
          pip install sphinx sphinx-pyproject furo
          # Provide fallback for theme
          pip install sphinx-rtd-theme
          pip install -e .
          
          # Create a temporary conf.py with fallback theme
          cd docs
          cp conf.py conf.py.backup
          python -c "
          content = open('conf.py', 'r').read()
          try:
              import furo
              print('Furo theme found, using it')
          except ImportError:
              print('Furo theme not found, using RTD theme as fallback')
              content = content.replace(\"html_theme = 'furo'\", \"html_theme = 'sphinx_rtd_theme'\")
              open('conf.py', 'w').write(content)
          "
          
          # Build docs
          make html
          
          # Restore original conf.py
          mv conf.py.backup conf.py
          cd ..
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4