name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Build and Publish TestPyPi"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest  # Ensure this is set correctly
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
        continue-on-error: true
        id: download

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- CRUCIAL: CHECK THE PLATFORM ---
      - name: Check Platform
        run: python -c "import platform; print(platform.system())"

      # Rebuild documentation if the artifact is not available
      - name: Build documentation if needed
        if: steps.download.outcome != 'success'
        run: |
          pip install -e ".[docs]"  # Correct installation with [docs] extra
          cd docs
          make html
          cd ..

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4